# .swiftlint.yml

included:
  - Sources
  - Tests

excluded:
  - .build
  - DerivedData

opt_in_rules:
  - attributes
  - closure_spacing
  - explicit_self
  - multiline_parameters
  - vertical_parameter_alignment
  - trailing_closure
  - unused_declaration

disabled_rules:
  - line_length
  - identifier_name
  - attributes  # Swift Testing uses inline attributes

large_tuple:
  warning: 3  # Allow up to 3 members in a tuple

reporter: xcode