codecov:
  require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 2%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: yes