name: Run Swift Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run Swift Tests
    runs-on: macos-latest

    steps:
      - name: Select Xcode 15.4
        run: sudo xcode-select -s /Applications/Xcode_15.4.app

      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Swift 6.1
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: '6.1"'

      - name: Run Swift Tests
        run: swift test --enable-code-coverage
