name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run tests on ${{ matrix.os }} - Swift ${{ matrix.swift }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]
        swift: ["5.10"]

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Swift ${{ matrix.swift }}
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: ${{ matrix.swift }}

      - name: Show Swift version
        run: swift --version

      - name: Build and test
        run: swift test --enable-code-coverage
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          flags: unittests
          verbose: true